### ISSUE TITLE
Error: incompatible with your PHP version

### ISSUE THREAD

**Issue by tiavina-mika** [coopTilleuls/UrlSignerBundle#8]
I got this error installing it

```
  [InvalidArgumentException]
  Package tilleuls/url-signer-bundle has a PHP requirement incompatible with your PHP version, PHP extensions and Composer version  
```

I'm using ``PHP 7.3.21``
Wich PHP version it's compatible with?

**Comment by thbil** [comment]
Hello,

This bundle requires php 7.4 (see: https://github.com/coopTilleuls/UrlSignerBundle/blob/main/composer.json#L26).
